#!/usr/bin/env python3
"""
L1 Slot Timing Analysis Tool

Analyzes L1 downlink slot timing from CSV files generated by nr-softmodem.
Provides detailed breakdown of processing stages with statistics.

Usage:
    python3 analyze_l1_slot_timing.py [OPTIONS] [csv_file]

Options:
    --rbs N         Filter to slots with N RBs
    --mcs N         Filter to slots with MCS N
    --summary       Show only summary (no detailed breakdown)
    --no-color      Disable colored output
    --json          Output as JSON
    --compare FILE  Compare with another CSV file
    -h, --help      Show help
"""

import csv
import sys
import json
import statistics
from dataclasses import dataclass, field
from collections import defaultdict
from typing import List, Dict, Optional, Tuple


# ============================================================================
# Terminal Colors
# ============================================================================

class Colors:
    """ANSI color codes for terminal output"""
    RESET = '\033[0m'
    BOLD = '\033[1m'
    DIM = '\033[2m'

    RED = '\033[91m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    WHITE = '\033[97m'

    BG_RED = '\033[41m'
    BG_GREEN = '\033[42m'

    _enabled = True

    @classmethod
    def disable(cls):
        cls._enabled = False

    @classmethod
    def c(cls, color: str, text: str) -> str:
        """Apply color to text if colors are enabled"""
        if not cls._enabled:
            return text
        return f"{color}{text}{cls.RESET}"


# ============================================================================
# Statistics Helper
# ============================================================================

@dataclass
class Stats:
    """Statistics for a set of timing values"""
    values: List[int] = field(default_factory=list)

    @property
    def count(self) -> int:
        return len(self.values)

    @property
    def non_zero(self) -> List[int]:
        return [v for v in self.values if v > 0]

    @property
    def min(self) -> int:
        return min(self.non_zero) if self.non_zero else 0

    @property
    def max(self) -> int:
        return max(self.non_zero) if self.non_zero else 0

    @property
    def mean(self) -> float:
        return statistics.mean(self.non_zero) if self.non_zero else 0

    @property
    def stdev(self) -> float:
        return statistics.stdev(self.non_zero) if len(self.non_zero) > 1 else 0

    def percentile(self, pct: int) -> int:
        if not self.non_zero:
            return 0
        sorted_vals = sorted(self.non_zero)
        idx = int(len(sorted_vals) * pct / 100)
        return sorted_vals[min(idx, len(sorted_vals) - 1)]

    @property
    def p50(self) -> int:
        return self.percentile(50)

    @property
    def p95(self) -> int:
        return self.percentile(95)

    @property
    def p99(self) -> int:
        return self.percentile(99)


def us(ns: float) -> str:
    """Format nanoseconds as microseconds with 2 decimal places"""
    return f"{ns / 1000:.2f}"


# ============================================================================
# Table Formatting
# ============================================================================

class Table:
    """Simple table formatter for timing output"""

    COLS = ['Stage', 'Min', 'Avg', 'P50', 'P95', 'P99', 'Max', '%']
    WIDTHS = [26, 9, 9, 9, 9, 9, 9, 7]

    def __init__(self, title: str, pct_label: str = 'Total'):
        self.title = title
        self.pct_label = pct_label
        self.rows: List[Tuple] = []

    def add(self, name: str, stats: Stats, total: float, indent: int = 0, note: str = ''):
        """Add a row with statistics"""
        if stats.mean == 0:
            return

        pct = 100 * stats.mean / total if total > 0 else 0
        prefix = '  ' * indent
        self.rows.append((
            f"{prefix}{name}",
            us(stats.min), us(stats.mean), us(stats.p50),
            us(stats.p95), us(stats.p99), us(stats.max),
            f"{pct:.1f}%", note
        ))

    def add_raw(self, name: str, values: List[str], note: str = ''):
        """Add a row with raw string values"""
        self.rows.append((name, *values, note))

    def add_separator(self):
        """Add a separator line"""
        self.rows.append(None)

    def render(self) -> str:
        """Render the table as a string"""
        if not self.rows:
            return ''

        lines = []

        # Header
        header_cols = self.COLS[:-1] + [f'%{self.pct_label}']
        header = ''.join(f"{col:>{self.WIDTHS[i]}}" for i, col in enumerate(header_cols))
        lines.append(Colors.c(Colors.BOLD, f"\n{self.title}"))
        lines.append(Colors.c(Colors.DIM, header))
        lines.append(Colors.c(Colors.DIM, '-' * sum(self.WIDTHS)))

        # Rows
        for row in self.rows:
            if row is None:
                lines.append(Colors.c(Colors.DIM, '-' * sum(self.WIDTHS)))
                continue

            name, *values = row[:8]
            note = row[8] if len(row) > 8 else ''

            # Format row
            line = f"{name:<{self.WIDTHS[0]}}"
            for i, val in enumerate(values):
                line += f"{val:>{self.WIDTHS[i + 1]}}"

            # Add note with color
            if note:
                if 'HIDDEN' in note or '✓' in note:
                    line += f"  {Colors.c(Colors.GREEN, note)}"
                elif 'overhead' in note or '⚠' in note:
                    line += f"  {Colors.c(Colors.YELLOW, note)}"
                else:
                    line += f"  {Colors.c(Colors.DIM, note)}"

            lines.append(line)

        return '\n'.join(lines)


# ============================================================================
# Data Loading
# ============================================================================

def load_csv(csv_file: str, filter_rbs: Optional[int] = None,
             filter_mcs: Optional[int] = None) -> Tuple[Dict[str, Stats], int, int]:
    """
    Load and filter CSV data, returning statistics for each field.

    Returns: (data_dict, total_slots, pdsch_slots)
    """
    data: Dict[str, Stats] = defaultdict(lambda: Stats(values=[]))
    total_slots = 0
    pdsch_slots = 0

    with open(csv_file, 'r') as f:
        reader = csv.DictReader(f)
        fields = reader.fieldnames or []

        for row in reader:
            total_slots += 1

            # Skip non-PDSCH slots
            num_pdsch = int(row.get('num_pdsch', 0))
            pdsch_gen = int(row.get('pdsch_gen_ns', 0))
            if pdsch_gen == 0 and num_pdsch == 0:
                continue

            # Apply filters
            num_rbs = int(row.get('num_rbs', 0))
            mcs = int(row.get('mcs', -1))

            if filter_rbs is not None and num_rbs != filter_rbs:
                continue
            if filter_mcs is not None and mcs != filter_mcs:
                continue

            pdsch_slots += 1

            # Collect all numeric fields
            for key in fields:
                try:
                    val = int(row.get(key, 0))
                    data[key].values.append(val)
                except (ValueError, TypeError):
                    pass

    return dict(data), total_slots, pdsch_slots


# ============================================================================
# Analysis Functions
# ============================================================================

def analyze_timing(data: Dict[str, Stats], total_slots: int, pdsch_slots: int) -> Dict:
    """Analyze timing data and return results"""

    if pdsch_slots == 0:
        return {'error': 'No PDSCH slots found'}

    # Determine total key
    total_key = 'total_slot_ns' if 'total_slot_ns' in data else 'total_ns'
    avg_total = data[total_key].mean if total_key in data else 1

    # Check for async format
    has_async = ('encoding_overlap_ns' in data and
                 any(v > 0 for v in data['encoding_overlap_ns'].values))

    results = {
        'slots': {'total': total_slots, 'pdsch': pdsch_slots},
        'has_async_format': has_async,
        'avg_total_us': avg_total / 1000,
        'stages': {},
    }

    # === Main stages ===
    main_stages = [
        ('mac_scheduler_ns', 'MAC Scheduler'),
        ('prs_gen_ns', 'PRS'),
        ('ssb_gen_ns', 'SSB'),
        ('pdcch_gen_ns', 'PDCCH'),
        ('pdsch_gen_ns', 'PDSCH'),
        ('csirs_gen_ns', 'CSI-RS'),
        ('phase_rot_ns', 'Phase Rotation'),
        ('ru_tx_total_ns', 'RU TX'),
    ]

    for key, name in main_stages:
        if key in data and data[key].mean > 0:
            results['stages'][name] = {
                'avg_us': data[key].mean / 1000,
                'pct': 100 * data[key].mean / avg_total,
            }

    # === Parallel section ===
    if has_async:
        enc_avg = data['encoding_overlap_ns'].mean
        wait_avg = data.get('memclear_wait_ns', Stats()).mean
        results['parallel'] = {
            'encoding_us': enc_avg / 1000,
            'wait_us': wait_avg / 1000,
            'critical_path_us': (enc_avg + wait_avg) / 1000,
            'hidden': wait_avg < 1000,  # < 1µs means fully hidden
        }

    # === Budget analysis ===
    total_vals = data[total_key].values if total_key in data else []
    slot_budget = 500000  # 500µs
    over_budget = [v for v in total_vals if v > slot_budget]

    results['budget'] = {
        'target_us': 500,
        'avg_us': avg_total / 1000,
        'within_budget': avg_total <= slot_budget,
        'margin_pct': 100 * (1 - avg_total / slot_budget),
        'over_budget_count': len(over_budget),
        'over_budget_pct': 100 * len(over_budget) / len(total_vals) if total_vals else 0,
        'p95_us': data[total_key].p95 / 1000 if total_key in data else 0,
        'p99_us': data[total_key].p99 / 1000 if total_key in data else 0,
        'max_us': data[total_key].max / 1000 if total_key in data else 0,
    }

    # === Find bottleneck ===
    if results['stages']:
        bottleneck = max(results['stages'].items(), key=lambda x: x[1]['avg_us'])
        results['bottleneck'] = {
            'stage': bottleneck[0],
            'avg_us': bottleneck[1]['avg_us'],
            'pct': bottleneck[1]['pct'],
        }

    return results


def print_analysis(data: Dict[str, Stats], total_slots: int, pdsch_slots: int,
                   filter_rbs: Optional[int] = None, filter_mcs: Optional[int] = None,
                   summary_only: bool = False):
    """Print detailed analysis to stdout"""

    if pdsch_slots == 0:
        print(Colors.c(Colors.YELLOW, f"⚠ No PDSCH slots found (filter: RBs={filter_rbs}, MCS={filter_mcs})"))
        return

    # Header
    filter_str = ''
    if filter_rbs is not None:
        filter_str += f" [RBs={filter_rbs}]"
    if filter_mcs is not None:
        filter_str += f" [MCS={filter_mcs}]"

    print(Colors.c(Colors.BOLD + Colors.CYAN, "=" * 90))
    print(Colors.c(Colors.BOLD, f"L1 SLOT TIMING: {pdsch_slots}/{total_slots} PDSCH slots{filter_str}"))
    print(Colors.c(Colors.BOLD + Colors.CYAN, "=" * 90))

    # Determine keys
    total_key = 'total_slot_ns' if 'total_slot_ns' in data else 'total_ns'
    avg_total = data[total_key].mean if total_key in data else 1

    has_async = ('encoding_overlap_ns' in data and
                 any(v > 0 for v in data['encoding_overlap_ns'].values))

    # === Parallel Section (Async Format) ===
    if has_async:
        tbl = Table("PARALLEL SECTION (Encoding || Memclear)", "Slot")

        enc_stats = data['encoding_overlap_ns']
        wait_stats = data.get('memclear_wait_ns', Stats())

        tbl.add('Encoding (LDPC+RM)', enc_stats, avg_total, note='(parallel)')

        wait_note = '✓ HIDDEN' if wait_stats.mean < 1000 else 'overhead'
        tbl.add('Memclear Wait', wait_stats, avg_total, note=wait_note)

        # Critical path
        critical = enc_stats.mean + wait_stats.mean
        critical_pct = 100 * critical / avg_total
        tbl.add_raw('→ Critical Path', ['', us(critical), '', '', '', '', f'{critical_pct:.1f}%'])

        print(tbl.render())

    # === Main Timing Breakdown ===
    if not summary_only:
        tbl = Table("MAIN TIMING BREAKDOWN", "Slot")

        main_stages = [
            ('mac_scheduler_ns', 'MAC Scheduler'),
            ('prs_gen_ns', 'PRS'),
            ('ssb_gen_ns', 'SSB'),
            ('pdcch_gen_ns', 'PDCCH'),
            ('pdsch_gen_ns', 'PDSCH'),
            ('csirs_gen_ns', 'CSI-RS'),
            ('phase_rot_ns', 'Phase Rotation'),
            ('ru_tx_total_ns', 'RU TX'),
        ]

        for key, name in main_stages:
            if key in data:
                tbl.add(name, data[key], avg_total)

        tbl.add_separator()
        tbl.add(Colors.c(Colors.BOLD, 'TOTAL'), data[total_key], avg_total)

        print(tbl.render())

    # === PDSCH Breakdown ===
    if not summary_only and 'pdsch_gen_ns' in data:
        avg_pdsch = data['pdsch_gen_ns'].mean

        tbl = Table("PDSCH BREAKDOWN", "PDSCH")

        pdsch_stages = [
            ('pdsch_encoding_ns', 'Encoding'),
            ('pdsch_scrambling_ns', 'Scrambling'),
            ('pdsch_modulation_ns', 'Modulation'),
            ('pdsch_layer_mapping_ns', 'Layer Mapping'),
            ('pdsch_precoding_ns', 'Precoding'),
            ('pdsch_re_mapping_ns', 'RE Mapping'),
        ]

        for key, name in pdsch_stages:
            if key in data and data[key].mean > 0:
                tbl.add(name, data[key], avg_pdsch, indent=1)

        # Check for skipped precoding (PMI=0 fast path)
        if 'pdsch_precoding_ns' in data and data['pdsch_precoding_ns'].mean == 0:
            tbl.add_raw('  Precoding', ['--', 'SKIPPED', '', '', '', '', ''], note='PMI=0 fast path')

        print(tbl.render())

    # === Encoding Breakdown ===
    enc_fields = ['enc_crc_ns', 'enc_segmentation_ns', 'enc_ldpc_ns']
    has_enc = any(k in data and data[k].mean > 0 for k in enc_fields)

    if not summary_only and has_enc:
        avg_enc = data.get('pdsch_encoding_ns', Stats()).mean or 1

        tbl = Table("ENCODING BREAKDOWN", "Enc")

        enc_stages = [
            ('enc_crc_ns', 'CRC'),
            ('enc_segmentation_ns', 'Segmentation'),
            ('enc_ldpc_ns', 'LDPC+RM+Intlv'),
        ]

        for key, name in enc_stages:
            if key in data and data[key].mean > 0:
                note = '(ACC100)' if 'ldpc' in key.lower() else ''
                tbl.add(name, data[key], avg_enc, indent=1, note=note)

        print(tbl.render())

    # === RU TX Breakdown ===
    if not summary_only and 'ru_tx_total_ns' in data and data['ru_tx_total_ns'].mean > 0:
        avg_ru = data['ru_tx_total_ns'].mean

        tbl = Table("RU TX BREAKDOWN", "RU")

        ru_stages = [
            ('feptx_prec_ns', 'FEPTX Prec'),
            ('feptx_ofdm_ns', 'FEPTX OFDM'),
            ('fh_south_out_ns', 'FH South Out'),
        ]

        for key, name in ru_stages:
            if key in data and data[key].mean > 0:
                tbl.add(name, data[key], avg_ru, indent=1)

        print(tbl.render())

    # === RB Distribution ===
    if not summary_only and 'num_rbs' in data:
        rb_vals = data['num_rbs'].non_zero
        if rb_vals:
            print(Colors.c(Colors.BOLD, f"\nRB DISTRIBUTION"))
            print(Colors.c(Colors.DIM, '-' * 50))
            print(f"  Range: {min(rb_vals)} - {max(rb_vals)} RBs (avg: {statistics.mean(rb_vals):.0f})")

            rb_counts = defaultdict(int)
            for rb in rb_vals:
                rb_counts[rb] += 1

            top_rbs = sorted(rb_counts.items(), key=lambda x: -x[1])[:3]
            if len(top_rbs) > 1:
                print(f"  Most common: {', '.join(f'{rb} RBs ({100*cnt/len(rb_vals):.0f}%)' for rb, cnt in top_rbs)}")

    # === Budget Analysis ===
    print(Colors.c(Colors.BOLD, f"\n500µs BUDGET"))
    print(Colors.c(Colors.DIM, '-' * 50))

    total_vals = data[total_key].values if total_key in data else []
    slot_budget = 500000  # 500µs
    avg_us = avg_total / 1000

    if avg_us > 500:
        print(Colors.c(Colors.RED, f"  ⚠ OVER BUDGET: {avg_us:.1f}µs avg (target: 500µs)"))
    else:
        margin = 100 * (1 - avg_us / 500)
        print(Colors.c(Colors.GREEN, f"  ✓ WITHIN BUDGET: {avg_us:.1f}µs avg ({margin:.1f}% margin)"))

    over_budget = [v for v in total_vals if v > slot_budget]
    if over_budget:
        pct = 100 * len(over_budget) / len(total_vals)
        print(Colors.c(Colors.YELLOW, f"  ⚠ {len(over_budget)} slots ({pct:.2f}%) exceeded 500µs"))
        print(f"    P95: {data[total_key].p95/1000:.1f}µs  P99: {data[total_key].p99/1000:.1f}µs  Max: {data[total_key].max/1000:.1f}µs")

    # === Bottleneck Summary ===
    print(Colors.c(Colors.BOLD, f"\nBOTTLENECK"))
    print(Colors.c(Colors.DIM, '-' * 50))

    stage_avgs = {}
    main_stages = [
        ('mac_scheduler_ns', 'MAC Scheduler'),
        ('prs_gen_ns', 'PRS'),
        ('ssb_gen_ns', 'SSB'),
        ('pdcch_gen_ns', 'PDCCH'),
        ('pdsch_gen_ns', 'PDSCH'),
        ('csirs_gen_ns', 'CSI-RS'),
        ('phase_rot_ns', 'Phase Rotation'),
        ('ru_tx_total_ns', 'RU TX'),
    ]

    # Include parallel section critical path
    if has_async:
        enc = data['encoding_overlap_ns'].mean
        wait = data.get('memclear_wait_ns', Stats()).mean
        stage_avgs['Enc+Memclear'] = enc + wait

    for key, name in main_stages:
        if key in data and data[key].mean > 0:
            stage_avgs[name] = data[key].mean

    if stage_avgs:
        bottleneck = max(stage_avgs, key=stage_avgs.get)
        bn_us = stage_avgs[bottleneck] / 1000
        bn_pct = 100 * stage_avgs[bottleneck] / avg_total
        print(f"  Main: {Colors.c(Colors.YELLOW, bottleneck)} ({bn_us:.1f}µs, {bn_pct:.1f}%)")

    # PDSCH sub-bottleneck
    if 'pdsch_gen_ns' in data:
        avg_pdsch = data['pdsch_gen_ns'].mean
        pdsch_avgs = {}
        for key, name in [('pdsch_encoding_ns', 'Encoding'), ('pdsch_re_mapping_ns', 'RE Mapping'),
                          ('pdsch_modulation_ns', 'Modulation'), ('pdsch_scrambling_ns', 'Scrambling')]:
            if key in data and data[key].mean > 0:
                pdsch_avgs[name] = data[key].mean

        if pdsch_avgs:
            bn = max(pdsch_avgs, key=pdsch_avgs.get)
            print(f"  PDSCH: {bn} ({pdsch_avgs[bn]/1000:.1f}µs, {100*pdsch_avgs[bn]/avg_pdsch:.1f}%)")

    print()


# ============================================================================
# Comparison Mode
# ============================================================================

def compare_csv(file1: str, file2: str, filter_rbs: Optional[int] = None,
                filter_mcs: Optional[int] = None):
    """Compare timing between two CSV files"""

    data1, _, pdsch1 = load_csv(file1, filter_rbs, filter_mcs)
    data2, _, pdsch2 = load_csv(file2, filter_rbs, filter_mcs)

    print(Colors.c(Colors.BOLD + Colors.CYAN, "=" * 90))
    print(Colors.c(Colors.BOLD, "COMPARISON"))
    print(Colors.c(Colors.BOLD + Colors.CYAN, "=" * 90))
    print(f"  File A: {file1} ({pdsch1} PDSCH slots)")
    print(f"  File B: {file2} ({pdsch2} PDSCH slots)")

    print(Colors.c(Colors.BOLD, f"\n{'Stage':<25} {'A (µs)':>10} {'B (µs)':>10} {'Δ (µs)':>10} {'Change':>10}"))
    print(Colors.c(Colors.DIM, '-' * 70))

    stages = [
        ('total_slot_ns', 'TOTAL'),
        ('pdsch_gen_ns', 'PDSCH'),
        ('ru_tx_total_ns', 'RU TX'),
        ('phase_rot_ns', 'Phase Rotation'),
        ('memory_clear_ns', 'Memory Clear'),
    ]

    for key, name in stages:
        if key not in data1 or key not in data2:
            continue

        avg1 = data1[key].mean / 1000
        avg2 = data2[key].mean / 1000
        delta = avg2 - avg1
        pct = 100 * delta / avg1 if avg1 > 0 else 0

        if delta < -1:  # Improvement > 1µs
            color = Colors.GREEN
            sign = ''
        elif delta > 1:  # Regression > 1µs
            color = Colors.RED
            sign = '+'
        else:
            color = Colors.DIM
            sign = '+' if delta >= 0 else ''

        delta_str = Colors.c(color, f"{sign}{delta:.1f}")
        pct_str = Colors.c(color, f"{sign}{pct:.1f}%")

        print(f"{name:<25} {avg1:>10.1f} {avg2:>10.1f} {delta_str:>10} {pct_str:>10}")


# ============================================================================
# Main
# ============================================================================

def main():
    import argparse

    parser = argparse.ArgumentParser(
        description='Analyze L1 slot timing from CSV files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s                           # Analyze l1_slot_timing.csv
  %(prog)s timing.csv --rbs 273      # Filter to 273 RBs
  %(prog)s --summary                 # Show only summary
  %(prog)s --compare old.csv         # Compare with another file
  %(prog)s --json                    # Output as JSON
        """
    )

    parser.add_argument('csv_file', nargs='?', default='l1_slot_timing.csv',
                        help='CSV file to analyze (default: l1_slot_timing.csv)')
    parser.add_argument('--rbs', type=int, help='Filter to slots with N RBs')
    parser.add_argument('--mcs', type=int, help='Filter to slots with MCS N')
    parser.add_argument('--summary', action='store_true', help='Show only summary')
    parser.add_argument('--no-color', action='store_true', help='Disable colored output')
    parser.add_argument('--json', action='store_true', help='Output as JSON')
    parser.add_argument('--compare', metavar='FILE', help='Compare with another CSV file')

    args = parser.parse_args()

    if args.no_color:
        Colors.disable()

    try:
        if args.compare:
            compare_csv(args.csv_file, args.compare, args.rbs, args.mcs)
        elif args.json:
            data, total, pdsch = load_csv(args.csv_file, args.rbs, args.mcs)
            results = analyze_timing(data, total, pdsch)
            print(json.dumps(results, indent=2))
        else:
            data, total, pdsch = load_csv(args.csv_file, args.rbs, args.mcs)
            print_analysis(data, total, pdsch, args.rbs, args.mcs, args.summary)

    except FileNotFoundError:
        print(Colors.c(Colors.RED, f"Error: '{args.csv_file}' not found"), file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(Colors.c(Colors.RED, f"Error: {e}"), file=sys.stderr)
        if '--debug' in sys.argv:
            import traceback
            traceback.print_exc()
        sys.exit(1)


if __name__ == '__main__':
    main()
